version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"  # Puerto expuesto en localhost
    networks:
      - lan_network  # Red personalizada `bridge`

  backend:
    build: .
    container_name: fastapi_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    ports:
      - "8000:8000"  # Puerto expuesto para FastAPI
    networks:
      - lan_network  # Red personalizada `bridge`

networks:
  lan_network:
    driver: bridge  # Usar red `bridge` personalizada para la comunicación entre contenedores
